#!/bin/bash
# =====================================
# Script to launch TrueCommand docker container
# Contact iXsystems (http://ixsystems.com) for assistance
# =====================================
# Configuration options
# ----------------------------
port="80"
sslport="443"
version="latest"
datadir="/data"
# ============

#Main Script
if [ "${1}" = "stop" ] ; then
  id=$(docker ps | grep "ixsystems/truecommand" | cut -d ' ' -f 1)
  echo "Stopping TrueCommand container: ${id}"
  docker stop "${id}"
  exit $?
fi

# Step 1 : Pull latest version (can fail as needed if internet access unavailable)
docker pull ixsystems/truecommand:latest

# Step 2 : Start the container
if [ ! -d "${datadir}" ] ; then
  mkdir "${datadir}"
  touch "${datadir}/.vm_wrapper" #in case we need to use this in the TC image for any special functionality later
fi

if [ "${1}" = "service" ] ; then
  #Do not detach from the process. Service needs to know when it is stopped and should be restarted
  docker run  -v "${datadir}:/data"-p "${port}:80" -p "${sslport}:443" "ixsystems/truecommand:${version}"

else
  #Manual run of the start script. Detach from the docker process
  docker run  --detach -v "${datadir}:/data" -p "${port}:80" -p "${sslport}:443"  "ixsystems/truecommand:${version}"
fi
